# Generated by Django 3.0.5 on 2020-12-10 13:46

import AttandanceData.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('password1', models.CharField(default='', max_length=150)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('facultyimage', models.FileField(default='', upload_to=AttandanceData.models.user_directory_faculty)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('password1', models.CharField(default='', max_length=150)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('studentimage', models.FileField(default='', upload_to=AttandanceData.models.user_directory_path)),
            ],
        ),
    ]
